name: Update Lunch Calendar

on:
  schedule:
    # Run at 6:00 AM UTC every day
    - cron: '0 6 * * *'
  # Allow manual trigger
  workflow_dispatch:
  # Run on push to main branch (useful for testing)
  push:
    branches: [ main ]

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run calendar update script
      run: python scraper.py

    - name: Create empty calendar file if it doesn't exist
      run: |
        if [ ! -f lunch_calendar.ics ]; then
          echo "Creating empty calendar file as fallback"
          python -c "
import icalendar
import datetime
import pytz
cal = icalendar.Calendar()
cal.add('prodid', '-//School Lunch Menu Calendar//example.com//')
cal.add('version', '2.0')
cal.add('X-WR-CALNAME', 'School Lunch Menu')
cal.add('X-WR-CALDESC', 'Daily school lunch menu items')
with open('lunch_calendar.ics', 'wb') as f:
  f.write(cal.to_ical())
          "
        fi

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add lunch_calendar.ics
        git commit -m "Update lunch calendar" || echo "No changes to commit"
        git push
