name: Update Lunch Calendar

on:
  schedule:
    # Run at 6:00 AM UTC every day
    - cron: '0 6 * * *'
  # Allow manual trigger
  workflow_dispatch:
  # Run on push to main branch (useful for testing)
  push:
    branches: [ main ]

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run calendar update script
      run: python scraper.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add lunch_calendar.ics
        # Continue even if there are no changes
        git commit -m "Update lunch calendar" || echo "No changes to commit"
        git push
